Algoritmo "semnome"
//  
//  
// Descrição   : impar ou par
// Autor(a)    : Gabriel parra
// Data atual  : 08/06/2020
Var
// Seção de Declarações das variáveis 

num : inteiro




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

//entrada

escreval("qual o numero: ")
leia(num)

//processamento

se (num mod 2) = 0 entao
   escreval("Par")
senao
     escreval("Impar")
fimse

//saida




Fimalgoritmo
